name: parabol_native
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Network
  dio: ^5.7.0
  
  # Routing
  go_router: ^14.6.0
  
  # Storage
  flutter_secure_storage: ^9.2.2
  
  # UI & Assets
  flutter_svg: ^2.0.17
  
  # Syncfusion
  syncfusion_flutter_charts: ^28.1.33
  syncfusion_flutter_datagrid: ^28.1.33
  syncfusion_flutter_core: ^28.1.33
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
